name: build and publish

on: 
  push:
    tags:
      - "*"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Set up build args
      run: |
        echo "MAJOR_VERSION=${GITHUB_REF_NAME%%.*}" >> $GITHUB_ENV
        echo "MINOR_VERSION=${GITHUB_REF_NAME%.*}" >> $GITHUB_ENV
        echo "BUILD_VERSION=${GITHUB_REF_NAME%-*}" >> $GITHUB_ENV
        echo "TAG_VERSION=${GITHUB_REF_NAME}" >> $GITHUB_ENV
        echo "BUILD_DATE=$(date +"%Y-%m-%d")" >> $GITHUB_ENV

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to ghcr.io
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: VergilGao
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        context: .
        file: ./Dockerfile
        platforms: linux/amd64
        tags: |
          ghcr.io/vergilgao/owntone-server:${{ env.MAJOR_VERSION }}
          ghcr.io/vergilgao/owntone-server:${{ env.MINOR_VERSION }}
          ghcr.io/vergilgao/owntone-server:${{ env.BUILD_VERSION }}
          ghcr.io/vergilgao/owntone-server:${{ env.TAG_VERSION }}
          ghcr.io/vergilgao/owntone-server:latest
        build-args: |
          VERSION=${{ env.BUILD_VERSION }}
          BUILD_DATE=${{ env.BUILD_DATE }}